apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot

spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: chatbot

  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          ports:
           - containerPort: 5000

